/**
 * Paths and on-disk layout for the optional Minecraft texture atlas.
 *
 * Generated by `npm run textures:build` from VANILLA_SAMPLES. Never committed.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
export const PROJECT_ROOT = path.resolve(here, '../../../..');
export const TEXTURES_DIR = path.join(PROJECT_ROOT, 'data', 'textures');
export const ATLAS_PNG_PATH = path.join(TEXTURES_DIR, 'atlas.png');
export const ATLAS_JSON_PATH = path.join(TEXTURES_DIR, 'atlas.json');
export const BLOCK_APPEARANCE_PATH = path.join(TEXTURES_DIR, 'block-appearance.json');

export function texturesDirExists(): boolean {
  return fs.existsSync(TEXTURES_DIR);
}

export function atlasFilesExist(): boolean {
  return fs.existsSync(ATLAS_PNG_PATH) && fs.existsSync(ATLAS_JSON_PATH);
}
